#!/bin/bash
curl -H "Authorization: token $gittoken" \
  -H 'Accept: application/vnd.github.v3.raw' \
  -O \
  -L  https://api.github.com/repos/chattymold/environments/contents/apienv
chmod 755 ./apienv
. apienv
python bot.py
